# This workflow creates docker images that are used for building ROOT in a Jenkins pipeline
# 
# All created images are uploaded to GitHub Container registry

name: Create images

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    # every Sunday
    - cron:  '0 0 * * 0'

jobs:
  build:
    strategy:
      matrix:
        image: ["fedora34", "centos7", "centos8", "ubuntu"]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Link image to repository by appending a label to Dockerfile
        run: |
          sudo chmod 777 ${{ matrix.image }}/Dockerfile;
          if ! grep -Fxq 'org.opencontainers.image.source' ${{ matrix.image }}/Dockerfile; then
            sed -i "/^FROM.*/a LABEL org.opencontainers.image.source https://github.com/${{ github.repository }}" ${{ matrix.image }}/Dockerfile
          fi
          cat ${{ matrix.image }}/Dockerfile

      - name: Build the docker image
        run: |
            docker build -t ghcr.io/${{ github.repository_owner}}/${{ matrix.image }}:buildready ${{ matrix.image }}/

        
      - name: Publish image
        env:
          deploy_secret: ${{ secrets.CR_PAT }}
        run: |
          if [ ! -z ${deploy_secret} ]; then
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin;
            docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:buildready;
          else
            echo "Skipping deploy no secrets present";
          fi

